export default function AboutPage() {
  return (
    <div
      id="about"
      className="flex flex-col container mx-auto mt-16 gap-8 h-[80vh] md:flex-row md:justify-between md:items-start  text-gray-50 md:gap-20"
    >
      <div className="flex flex-col items-start gap-8 md:w-1/2 text-left">
        <div className="flex flex-col gap-6">
          <h1 className="text-5xl text-center w-full font-bold md:w-96 md:text-left md:text-7xl">
            Cashless
          </h1>
          <p className="text-xl text-gray-400 md:w-80">
            is a 100% digital bank that seeks to make people's financial lives
            easier. The main function of the brand is to free its users from
            high fees and lack of customer services generated by conventional or
            traditional banks.
          </p>
        </div>
      </div>
      <div className="h-1/2 md:h-96 md:w-1/2  justify-self-end m-0">
        <div className="flex items-center justify-center text-3xl font-bold font-cursive bg-gray-100 w-full h-full bg-opacity-50 rounded-3xl">
          Illustration
        </div>
      </div>
    </div>
  );
}
